version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    labels:
      - "github actions"
    commit-message:
      prefix: "🤖 "
    groups:
      actions:
        patterns: ["*"]
